New Port: Pokemon Reborn
PortsMaster-MV/PortMaster-MV-New pull request #47
Opened 2024-10-06 19:05 UTC by JanTrueno

# New Port for Pokemon Reborn

## Game Information
- **Title**: Pokemon Reborn
- **URL**: https://www.rebornevo.com/pr/index.html/

## Submission Requirements

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] ROCKNIX
- [X] muOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

2024-10-10 15:04 UTC, cdeletre requested changes

2024-10-10 15:04 UTC, cdeletre commented on ports/reborn/reborn/preset/mkxp.json
> +     "JITMinCalls": 5000,
Last entry I think if my sight is good.
```suggestion
     "JITMinCalls": 5000
```

2024-10-10 15:04 UTC, cdeletre commented on ports/reborn/Pokemon Reborn.sh
> +printf "\033c" > /dev/tty0
Can be removed
```suggestion
```

2024-10-10 19:31 UTC, JeodC approved these changes

2024-10-11 01:52 UTC, cdeletre approved these changes

2024-10-11 12:44 UTC, JeodC approved these changes

2024-10-11 12:48 UTC, merged