Harkinians: add imgui.ini adjustments during launch
PortsMaster-MV/PortMaster-MV-New pull request #49
Opened 2024-10-22 00:24 UTC by JeodC

This change modifies `imgui.ini` during launch to ensure all imgui windows stay within the display bounds.

2024-10-22 17:31 UTC, cdeletre requested changes
Not sure why soh2 is like reversing to the old sh launch template. Any good reason ? :)

2024-10-22 17:31 UTC, cdeletre commented on ports/soh2/Ship of Harkinian 2.sh
Applying the new launch script template 

```suggestion
[ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
get_controls
```

2024-10-22 17:31 UTC, cdeletre commented on ports/soh2/Ship of Harkinian 2.sh
> +$GPTOKEYB "2s2h.elf" -c "soh2.gptk" &
Maybe there is a good reason to remove it, just tell me :)
```suggestion
pm_platform_helper "2s2h.elf"
$GPTOKEYB "2s2h.elf" -c "soh2.gptk" & 
```

2024-10-22 17:31 UTC, cdeletre commented on ports/soh2/Ship of Harkinian 2.sh
> +printf "\033c" > /dev/tty0
Same remark, just tell me if I'm wrong :)
```suggestion
pm_finish
```

2024-10-22 18:59 UTC, cdeletre approved these changes

2024-10-23 05:17 UTC, Cebion approved these changes

2024-10-23 05:17 UTC, merged