Update AM2R.sh
PortsMaster-MV/PortMaster-MV-New pull request #68
Opened 2024-12-31 15:42 UTC by JeodC

Modernize am2r.sh

2024-12-31 15:53 UTC, kloptops requested changes

2024-12-31 15:53 UTC, kloptops commented on ports/am2r/AM2R.sh
> +bind_directories "~/.config" "$GAMEDIR/conf/am2r"
```suggestion
bind_directories "~/.config/am2r" "$GAMEDIR/conf/am2r"
```

2024-12-31 16:07 UTC, kloptops approved these changes

2025-01-05 00:27 UTC, cdeletre approved these changes

2025-01-05 00:29 UTC, merged